### ISSUE TITLE
打包运行报错

### ISSUE THREAD

**Issue by Zvirtuey** [chenBingX/SuperTextView#102]
版本：implementation 'com.github.chenBingX:SuperTextView:v3.2.5.99'

调试debug都没问题，但是打包运行直接就奔溃了，加载界面xml就报错

2020-12-02 18:11:40.238 22069-22069/? E/Tag: Class load success!
2020-12-02 18:11:40.238 22069-22069/? E/zygote: ----- class 'Lcom/coorchice/library/gifdecoder/JNI;' cl=0x13a40230 -----
2020-12-02 18:11:40.238 22069-22069/? E/zygote:   objectSize=172 (172 from super)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:   access=0x0008.0001
2020-12-02 18:11:40.238 22069-22069/? E/zygote:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:   vtable (0 entries, 11 in super):
2020-12-02 18:11:40.238 22069-22069/? E/zygote:   direct methods (10 entries):
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      0: void com.coorchice.library.gifdecoder.JNI.<clinit>()
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      1: boolean com.coorchice.library.gifdecoder.JNI.bytesIsGif(byte[])
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      2: long com.coorchice.library.gifdecoder.JNI.copy(long)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      3: void com.coorchice.library.gifdecoder.JNI.copyDestroy(long)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      4: void com.coorchice.library.gifdecoder.JNI.destroy(long)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      5: int com.coorchice.library.gifdecoder.JNI.getHeight(long)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      6: int com.coorchice.library.gifdecoder.JNI.getWidth(long)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      7: void com.coorchice.library.gifdecoder.JNI.gotoFrame(long, int, android.graphics.Bitmap)
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      8: long com.coorchice.library.gifdecoder.JNI.openBytes(byte[])
2020-12-02 18:11:40.238 22069-22069/? E/zygote:      9: int com.coorchice.library.gifdecoder.JNI.updateFrame(long, android.graphics.Bitmap)
2020-12-02 18:11:40.238 22069-22069/? E/zygote: Failed to register native method com.coorchice.library.gifdecoder.JNI.openFile(Ljava/lang/String;)J in /data/app/com.rzt.newborn-SH_o0kO_Fo8rX4hWlQho3w==/base.apk
2020-12-02 18:11:40.239 22069-22069/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rzt.newborn, PID: 22069
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rzt.newborn/com.rzt.newborn.activity.SettingServerActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.c(AppCompatDelegateImpl.java:9)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
        at com.rzt.newborn.base.SuperActivity.setContentView(SuperActivity.java:1)
        at com.rzt.newborn.base.SuperActivity.onCreate(SuperActivity.java:2)
        at android.app.Activity.performCreate(Activity.java:7066)
        at android.app.Activity.performCreate(Activity.java:7057)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: java.lang.NoSuchMethodError: no static or non-static method "Lcom/coorchice/library/gifdecoder/JNI;.openFile(Ljava/lang/String;)J"
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.doLoad(Runtime.java:1099)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.coorchice.library.gifdecoder.JNI.<clinit>(JNI.java:1)
        at com.coorchice.library.gifdecoder.JNI.bytesIsGif(Native Method)
        at e.b.a.b.c.a(GifDecoder.java:21)
        at com.coorchice.library.SuperTextView.b(SuperTextView.java:156)
        at com.coorchice.library.SuperTextView.b(SuperTextView.java:22)
        at com.coorchice.library.SuperTextView.a(SuperTextView.java:4)
        at com.coorchice.library.SuperTextView.<init>(SuperTextView.java:48)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.c(AppCompatDelegateImpl.java:9) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1) 
        at com.rzt.newborn.base.SuperActivity.setContentView(SuperActivity.java:1) 
        at com.rzt.newborn.base.SuperActivity.onCreate(SuperActivity.java:2) 
        at android.app.Activity.performCreate(Activity.java:7066) 
        at android.app.Activity.performCreate(Activity.java:7057) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
2020-12-02 18:11:40.244 22069-22069/? W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rzt.newborn/com.rzt.newborn.activity.SettingServerActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.app.ActivityThread.-wrap12(Unknown Source:0)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.os.Looper.loop(Looper.java:192)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6842)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2020-12-02 18:11:40.244 22069-22069/? W/System.err: Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
2020-12-02 18:11:40.244 22069-22069/? W/System.err: Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.coorchice.library.SuperTextView
2020-12-02 18:11:40.244 22069-22069/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
2020-12-02 18:11:40.244 22069-22069/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.c(AppCompatDelegateImpl.java:9)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.rzt.newborn.base.SuperActivity.setContentView(SuperActivity.java:1)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.rzt.newborn.base.SuperActivity.onCreate(SuperActivity.java:2)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7066)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7057)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.ActivityThread.-wrap12(Unknown Source:0)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.os.Looper.loop(Looper.java:192)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6842)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2020-12-02 18:11:40.245 22069-22069/? W/System.err: Caused by: java.lang.NoSuchMethodError: no static or non-static method "Lcom/coorchice/library/gifdecoder/JNI;.openFile(Ljava/lang/String;)J"
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:1099)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at java.lang.System.loadLibrary(System.java:1657)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.gifdecoder.JNI.<clinit>(JNI.java:1)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.gifdecoder.JNI.bytesIsGif(Native Method)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at e.b.a.b.c.a(GifDecoder.java:21)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.SuperTextView.b(SuperTextView.java:156)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.SuperTextView.b(SuperTextView.java:22)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.SuperTextView.a(SuperTextView.java:4)
2020-12-02 18:11:40.245 22069-22069/? W/System.err:     at com.coorchice.library.SuperTextView.<init>(SuperTextView.java:48)
2020-12-02 18:11:40.245 22069-22069/? W/System.err: 	... 27 more

**Comment by Zvirtuey** [comment]
混淆文件加上这就好了     -keep class com.coorchice.library.gifdecoder.JNI { *; }

**Comment by mtj956052456** [comment]
并没有解决问题

**Comment by mtj956052456** [comment]
不开启混淆，为什么打包还是会出现问题？
