### ISSUE TITLE
在设置纯色背景图时崩溃, 请问该如何解决

### ISSUE THREAD

**Issue by Joehaivo** [chenBingX/SuperTextView#45]
崩溃log：
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.coorchice.library.utils.STVUtils.drawableToBitmap(STVUtils.java:44)
        at com.coorchice.library.SuperTextView.drawDrawableBackground(SuperTextView.java:528)
        at com.coorchice.library.SuperTextView.drawStateDrawable(SuperTextView.java:485)
        at com.coorchice.library.SuperTextView.onDraw(SuperTextView.java:318)
        at android.view.View.draw(View.java:20261)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
...

场景：
xml中：
<com.coorchice.library.SuperTextView
            android:id="@+id/iv_lamp_curr_color"
            android:layout_width="@dimen/dp_40"
            android:layout_height="@dimen/dp_40"
            android:layout_marginStart="@dimen/dp_40"
            android:layout_marginBottom="@dimen/dp_40"
            android:scaleType="centerCrop"
            app:stv_corner="@dimen/dp_5"
            app:stv_drawableAsBackground="true"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent" />

Java中：
mIvCurrColor.setDrawable(new ColorDrawable(solid));

PS： 不想使用 mIvCurrColor.setSolid(solid); 方法，只想控制SuperTextView的Drawable层显示内容

**Comment by chenBingX** [comment]
Hi，你好，
  感谢使用 SuperTextView，你反馈的问题 CoorChice 在持续跟进。  
  
  目前发布了最新版 v3.1.5 中修复了这个问题，建议更新到最新版本。  

  替换 build.gradle 中的依赖为：  

  ```
  dependencies {
	        implementation 'com.github.chenBingX:SuperTextView:3.1.5'
	}
  ```
