### ISSUE TITLE
请问一下这是什么原因造成的

### ISSUE THREAD

**Issue by LelandLi** [chenBingX/SuperTextView#56]
java.lang.IllegalArgumentException: y must be >= 0
        at android.graphics.Bitmap.checkXYSign(Bitmap.java:362)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:664)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
        at com.coorchice.library.SuperTextView.computeSuitedBitmapSize(SuperTextView.java:570)
        at com.coorchice.library.SuperTextView.drawDrawableBackground(SuperTextView.java:544)
        at com.coorchice.library.SuperTextView.drawStateDrawable(SuperTextView.java:496)
        at com.coorchice.library.SuperTextView.onDraw(SuperTextView.java:325)
        at android.view.View.draw(View.java:15495)
        at android.view.View.updateDisplayListIfDirty(View.java:14384)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.View.draw(View.java:15204)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3532)

**Comment by chenBingX** [comment]
建议更新到最新 v3.1.6.2 版本。依赖：com.github.chenbingx:supertextview:v3.1.6.2
