### ISSUE TITLE
设置圆形时报错

### ISSUE THREAD

**Issue by Borninthesun** [chenBingX/SuperTextView#77]
android.view.InflateException: Binary XML file line #37: Error inflating class <unknown>

**Comment by Papa1998** [comment]
不知道是bug还是使用的问题，把版本调低一点就不会报异常，我试了几个版本，3.1.6、3.1.5、3.1.4不会报错，版本高的话都会报异常，希望能帮到你

**Comment by chenBingX** [comment]
是否方便把相关代码贴出来（如果包含敏感信息可以构建一个测试版本），以及出现问题时所使用的版本，这样有助于问题的进一步定位。

**Comment by Papa1998** [comment]
不好意思，现在才看到邮件，我当时用了最新版本的STV，也报的顶楼这个错，然后自己测试了上面的几个版本评论的，不过很抱歉的是我忘记当时是怎么测试的了，因为没有保存，刚刚照着模糊的印象测试，但还是没有找到当时的错误信息，如果有后续的话我会及时提交的

**Comment by chenBingX** [comment]
好的，感谢您的持续关注😄

**Comment by Zvirtuey** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.coorchice.library.SuperTextView
        android:id="@+id/stv_back"
        android:layout_width="wrap_content"
        android:layout_height="45dp"
        android:gravity="center_vertical"
        android:paddingLeft="@dimen/back_left_width"
        android:text="@string/login"
        android:textColor="@color/black"
        android:textSize="16sp"
        app:stv_isShowState="true"
        app:stv_state_drawable="@drawable/icon_back"
        app:stv_state_drawable_height="26dp"
        app:stv_state_drawable_mode="left"
        app:stv_state_drawable_padding_left="5dp"
        app:stv_state_drawable_width="26dp" />

</LinearLayout>


我来提提吧，调试的时候试用没问题，但是打包的时候出现了这个问题

2020-11-27 10:10:55:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rzt.newborn/com.rzt.newborn.activity.SettingServerActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.c(AppCompatDelegateImpl.java:9)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
	at com.rzt.newborn.base.SuperActivity.setContentView(SuperActivity.java:1)
	at com.rzt.newborn.base.SuperActivity.onCreate(SuperActivity.java:2)
	at android.app.Activity.performCreate(Activity.java:7066)
	at android.app.Activity.performCreate(Activity.java:7057)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.NoSuchMethodError: no static or non-static method "Lcom/coorchice/library/gifdecoder/JNI;.openFile(Ljava/lang/String;)J"
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.doLoad(Runtime.java:1099)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
	at java.lang.System.loadLibrary(System.java:1657)
	at com.coorchice.library.gifdecoder.JNI.<clinit>(JNI.java:1)
	at com.coorchice.library.gifdecoder.JNI.bytesIsGif(Native Method)
	at e.b.a.b.c.a(GifDecoder.java:21)
	at com.coorchice.library.SuperTextView.b(SuperTextView.java:156)
	at com.coorchice.library.SuperTextView.b(SuperTextView.java:22)
	at com.coorchice.library.SuperTextView.a(SuperTextView.java:4)
	at com.coorchice.library.SuperTextView.<init>(SuperTextView.java:48)
	... 27 more
