### ISSUE TITLE
RecyclerView中无法使用状态图

### ISSUE THREAD

**Issue by Vicent9920** [chenBingX/SuperTextView#80]
在列表的item中使用SuperTextView作为根布局，加载失败，添加父布局之后依然无法生成，后来测试是因为使用了状态图导致无法实例化该控件。详情见日志：
```
android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.chad.library.adapter.base.util.AdapterUtilsKt.getItemView(AdapterUtils.kt:15)
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.kt:584)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.kt:580)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:249)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:74)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6949)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6001)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5997)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2227)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:563)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:172)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4032)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3444)
        at android.view.View.measure(View.java:22024)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22024)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22024)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22024)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
        at android.view.View.measure(View.java:22024)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2446)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1534)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1422)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6834)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
2020-02-21 17:52:48.914 16524-16524/com.cn.dcjt.firelibrary E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cn.dcjt.firelibrary-GMBV6WUgZG3rQ0z4EzLmHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.cn.dcjt.firelibrary-GMBV6WUgZG3rQ0z4EzLmHQ==/lib/arm64, /data/app/com.cn.dcjt.firelibrary-GMBV6WUgZG3rQ0z4EzLmHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libGifLib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.coorchice.library.gifdecoder.JNI.<clinit>(JNI.java:30)
        at com.coorchice.library.gifdecoder.JNI.bytesIsGif(Native Method)
        at com.coorchice.library.gifdecoder.GifDecoder.isGif(GifDecoder.java:444)
        at com.coorchice.library.SuperTextView.innerSetDrawable(SuperTextView.java:1481)
        at com.coorchice.library.SuperTextView.initAttrs(SuperTextView.java:257)
        at com.coorchice.library.SuperTextView.init(SuperTextView.java:225)
        at com.coorchice.library.SuperTextView.<init>(SuperTextView.java:194)
        	... 57 more
```
布局：
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <com.coorchice.library.SuperTextView
        android:id="@+id/root_view"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        android:padding="6dp"
        app:stv_corner="3dp"
        app:stv_stroke_width="1dp"
        app:stv_stroke_color="@color/gray_ccc"
        app:stv_isShowState="true"
        app:stv_state_drawable="@drawable/ic_item_selected"
        app:stv_state_drawable_height="20dp"
        app:stv_state_drawable_mode="left"
        app:stv_state_drawable_padding_left="10dp"
        app:stv_state_drawable_width="20dp"
        android:gravity="center"
        android:text="测试内容"
        android:textSize="12sp"
        android:textColor="#046DF0"/>



</RelativeLayout>
```

**Comment by Vicent9920** [comment]
修改版本号（由3.2.5修改为3.2.5.64）之后解决，建议在功能或者最新版本的地方注明状态图的so问题

**Comment by SemiraChen** [comment]
所以是为什么
