### ISSUE TITLE
2020 3/12 日最新版本demo gif演示页面闪退

### ISSUE THREAD

**Issue by xumengyin** [chenBingX/SuperTextView#81]
hi,手机小米4，android 6.0进入gif页面经常闪退

Process: com.coorchice.supertextview, PID: 26735
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.coorchice.supertextview/com.coorchice.supertextview.GifListActivity}: android.view.InflateException: Binary XML file line #203: Binary XML file line #203: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2483)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
        at android.app.ActivityThread.access$1000(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: android.view.InflateException: Binary XML file line #203: Binary XML file line #203: Error inflating class <unknown>
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
        at android.app.Activity.setContentView(Activity.java:2237)
        at com.coorchice.supertextview.GifListActivity.onCreate(GifListActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:6362)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: android.view.InflateException: Binary XML file line #203: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:649)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
        at android.app.Activity.setContentView(Activity.java:2237) 
        at com.coorchice.supertextview.GifListActivity.onCreate(GifListActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6362) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
        at android.app.Activity.setContentView(Activity.java:2237) 
        at com.coorchice.supertextview.GifListActivity.onCreate(GifListActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6362) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1904412 byte allocation with 727456 free bytes and 710KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:820)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
        at com.coorchice.library.gifdecoder.GifDecoder.init(GifDecoder.java:128)
        at com.coorchice.library.gifdecoder.GifDecoder.<init>(GifDecoder.java:121)
        at com.coorchice.library.gifdecoder.GifDecoder.copy(GifDecoder.java:90)
        at com.coorchice.library.gifdecoder.GifDrawable.copy(GifDrawable.java:77)
        at com.coorchice.library.gifdecoder.GifCache.fromResource(GifCache.java:171)
        at com.coorchice.library.SuperTextView.innerSetDrawable2(SuperTextView.java:1520)
        at com.coorchice.library.SuperTextView.initAttrs(SuperTextView.java:286)
        at com.coorchice.library.SuperTextView.init(SuperTextView.java:225)
        at com.coorchice.library.SuperTextView.<init>(SuperTextView.java:194)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
        at android.app.Activity.setContentView(Activity.java:2237) 
        at com.coorchice.supertextview.GifListActivity.onCreate(GifListActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6362) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by chenBingX** [comment]
你可以先尝试删除 https://github.com/chenBingX/SuperTextView/blob/master/app/src/main/res/layout/activity_gif_list.xml 中 #203 位置处的元素，看崩溃是否仍然在继续发生。在我的几个测试设备中都无法复现出这个问题。如果仍然有崩溃，还请麻烦再次提供下错误日志。
